services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb:bullseye
    environment:
      MARIADB_ROOT_HOST: ${MARIADB_ROOT_HOST}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD} 
      MARIADB_DATABASE: ${MARIADB_DATABASE} 
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - "mariadb-volume:/var/lib/mysql"
    networks:
      - inception
    restart: always
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx:bullseye
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - "wordpress-volume:/var/www/wordpress"
    networks:
      - inception
    restart: always
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress:bullseye
    environment:
      MARIADB_ROOT_HOST: ${MARIADB_ROOT_HOST}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USR: ${WP_ADMIN_USR}
      WP_ADMIN_PWD: ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USR: ${WP_USR}
      WP_PWD: ${WP_PWD}
      WP_EMAIL: ${WP_EMAIL}
    depends_on:
      - mariadb
    volumes:
      - "wordpress-volume:/var/www/wordpress"
    networks:
      - inception
    restart: always
volumes:
  mariadb-volume:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DB_HOST_VOLUME_PATH}
  wordpress-volume:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${WP_HOST_VOLUME_PATH}
networks:
  inception:
    driver: bridge
    name: inception
